title: 作品集 @Mina
logo: /assets/img/logo.jpg
description: 嗨！我是Mina！作為Python 後端工程師已有兩年多的工作經驗，這是我的作品集，將列出並解釋所有我參與過的產品與專案，以及我個人獨立開發的作品，有些附上網址，可供參考。
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal